name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.1.0+1
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  dart_style: ^2.3.3
  dartx: ^1.1.0
  glob: ^2.0.2
  isar: 3.1.0+1
  path: ^1.8.3
  source_gen: ^1.2.2
  xxh3: ^1.0.1

dev_dependencies:
  build_test: ^2.2.1
  matcher: ^0.12.16
  test: ^1.21.0
  very_good_analysis: ^5.1.0
